# Generated by Django 6.1 on 2026-08-13 14:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='grand_total',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='quotationitem',
            old_name='discount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='quotationitem',
            old_name='gst_rate',
            new_name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='converted_to_order',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='product_code',
        ),
        migrations.AddField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(default='Nos', max_length=30),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Expired', 'Expired'), ('Converted', 'Converted')], default='Draft', max_length=20),
        ),
    ]
