# Generated by Django 6.1 on 2026-08-13 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_number', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(default='Belt Conveyor', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('conveyor_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conveyor_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motor_hp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Production', 'In Production'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('materials_required', models.TextField(blank=True, null=True)),
                ('assigned_worker', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='orders.order')),
            ],
        ),
    ]
