# Generated by Django 6.1 on 2026-08-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('order', 'Order'), ('quotation', 'Quotation'), ('invoice', 'Invoice'), ('service', 'Service'), ('production', 'Production'), ('customer', 'Customer'), ('product', 'Product'), ('other', 'Other')], max_length=30)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('word', 'Word'), ('image', 'Image'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='historical_records/%Y/%m/')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
