# Generated by Django 6.1 on 2026-08-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-document_date', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='document',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='customer_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('order', 'Order'), ('quotation', 'Quotation'), ('invoice', 'Invoice'), ('service', 'Service'), ('production', 'Production'), ('customer', 'Customer'), ('product', 'Product'), ('other', 'Other')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
