# Generated by Django 6.1 on 2026-08-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('order_date', models.DateField()),
                ('product_name', models.CharField(default='Belt Conveyor', max_length=200)),
                ('conveyor_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conveyor_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motor_hp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Production', 'Production'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
